### ISSUE TITLE
[BrowsermobProxy] Unexpected expiration of an internally generated certificate

### ISSUE THREAD

**Issue by tkohegyi** [epam/Wilma#12]
Seems there is an internally created certificate in Wilma that was expired after Wilma runs for several weeks without interruption.

And suddenly this has happened at a application:

```
Caused by: org.springframework.remoting.RemoteAccessException: Could not access remote service at https://serviceurl; nested exception is com.sun.xml.internal.ws.client.ClientTransportException: HTTP transport error: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed
at org.springframework.remoting.jaxws.JaxWsPortClientInterceptor.doInvoke(JaxWsPortClientInterceptor.java:510) ~[spring-web-3.1.4.jar:3.1.4.RELEASE]
at org.springframework.remoting.jaxws.JaxWsPortClientInterceptor.invoke(JaxWsPortClientInterceptor.java:487) ~[spring-web-3.1.4.jar:3.1.4.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.1.4.jar:3.1.4.RELEASE]
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[spring-aop-3.1.4.jar:3.1.4.RELEASE]
....
Caused by: com.sun.xml.internal.ws.client.ClientTransportException: HTTP transport error: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed
at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:117) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:194) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:122) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:95) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Fiber.java:626) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Fiber.java:585) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Fiber.java:570) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Fiber.java:467) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.client.Stub.process(Stub.java:308) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.client.sei.SEIStub.doProcess(SEIStub.java:146) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:98) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:129) ~[na:1.7.0_25]
at com.sun.proxy.$Proxy162.registerCreditCard(Unknown Source) ~[na:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_25]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_25]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_25]
at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_25]
at org.springframework.remoting.jaxws.JaxWsPortClientInterceptor.doInvoke(JaxWsPortClientInterceptor.java:526) ~[spring-web-3.1.4.jar:3.1.4.RELEASE]
at org.springframework.remoting.jaxws.JaxWsPortClientInterceptor.doInvoke(JaxWsPortClientInterceptor.java:500) ~[spring-web-3.1.4.jar:3.1.4.RELEASE]
... 310 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed
at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.7.0_25]
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1886) ~[na:1.7.0_25]
at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276) ~[na:1.7.0_25]
at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270) ~[na:1.7.0_25]
at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1341) ~[na:1.7.0_25]
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:153) ~[na:1.7.0_25]
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868) ~[na:1.7.0_25]
at sun.security.ssl.Handshaker.process_record(Handshaker.java:804) ~[na:1.7.0_25]
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016) ~[na:1.7.0_25]
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312) ~[na:1.7.0_25]
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339) ~[na:1.7.0_25]
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323) ~[na:1.7.0_25]
at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:515) ~[na:1.7.0_25]
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.7.0_25]
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1090) ~[na:1.7.0_25]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250) ~[na:1.7.0_25]
at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:105) ~[na:1.7.0_25]
... 329 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed
at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:350) ~[na:1.7.0_25]
at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:260) ~[na:1.7.0_25]
at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.7.0_25]
at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326) ~[na:1.7.0_25]
```

**Comment by tkohegyi** [comment]
Ad 1 the workaround works smoothly, no strong demand on "fixing" this issue
Ad 2 ticket #76 will most probably resolve this issue too

Therefore it is decided to be closed as not important one.
