### ISSUE TITLE
Remove unnecessary stack trace in case of FIS decompression error

### ISSUE THREAD

**Issue by tkohegyi** [epam/Wilma#44]
When - due to error-nous - FIS request or response arrives, avoid flushing the whole stack-trace into the log.
```
13:51:14.361 [reponseJmsContainer-3] INFO  c.e.w.c.p.entity.MessageExtractor - Failed to extract message content! Restoring original content...
com.epam.wilma.domain.exception.SystemException: Could not perform fastinfoset decompression!
	at com.epam.wilma.compression.fis.FastInfosetCompressionService.decompress(FastInfosetCompressionService.java:98) ~[wilma-1.1.24.jar:na]
	at com.epam.wilma.core.processor.entity.FastInfosetDecompressorProcessor.process(FastInfosetDecompressorProcessor.java:47) ~[wilma-1.1.24.jar:na]
	at com.epam.wilma.core.processor.entity.MessageExtractor.extract(MessageExtractor.java:60) ~[wilma-1.1.24.jar:na]
	at com.epam.wilma.core.processor.response.jms.ResponseQueueListener.onMessage(ResponseQueueListener.java:64) [wilma-1.1.24.jar:na]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:699) [wilma-1.1.24.jar:na]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:637) [wilma-1.1.24.jar:na]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:605) [wilma-1.1.24.jar:na]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:308) [wilma-1.1.24.jar:na]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:246) [wilma-1.1.24.jar:na]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1144) [wilma-1.1.24.jar:na]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1136) [wilma-1.1.24.jar:na]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1033) [wilma-1.1.24.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: net.sf.saxon.trans.XPathException: I/O error reported by XML parser processing null: Unexpeceted EOF
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:467) ~[wilma-1.1.24.jar:na]
	at net.sf.saxon.event.Sender.send(Sender.java:145) ~[wilma-1.1.24.jar:na]
	at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:363) ~[wilma-1.1.24.jar:na]
	at com.epam.wilma.compression.fis.FastInfosetCompressionService.decompress(FastInfosetCompressionService.java:94) ~[wilma-1.1.24.jar:na]
	... 12 common frames omitted
Caused by: java.io.EOFException: Unexpeceted EOF
	at com.sun.xml.fastinfoset.Decoder.ensureOctetBufferSize(Decoder.java:1429) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.Decoder.decodeUtf8StringAsCharBuffer(Decoder.java:1386) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processUtf8CharacterString(SAXDocumentParser.java:1131) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processEII(SAXDocumentParser.java:922) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processEII(SAXDocumentParser.java:898) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processEII(SAXDocumentParser.java:898) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processEII(SAXDocumentParser.java:898) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processEII(SAXDocumentParser.java:898) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processEII(SAXDocumentParser.java:898) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processEII(SAXDocumentParser.java:892) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processEII(SAXDocumentParser.java:892) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processEII(SAXDocumentParser.java:909) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processEII(SAXDocumentParser.java:909) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processEIIWithNamespaces(SAXDocumentParser.java:1239) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.processDII(SAXDocumentParser.java:470) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.parse(SAXDocumentParser.java:399) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.parse(SAXDocumentParser.java:350) ~[wilma-1.1.24.jar:na]
	at com.sun.xml.fastinfoset.sax.SAXDocumentParser.parse(SAXDocumentParser.java:325) ~[wilma-1.1.24.jar:na]
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:440) ~[wilma-1.1.24.jar:na]
	... 15 common frames omitted
```

In case the root cause is `Caused by: java.io.EOFException: Unexpeceted EOF`, then it would be enough just saying that FIS decompression was not performed, and identify the message by its Wilma Logger ID.

**Comment by tkohegyi** [comment]
Won't fix. This error log is essential.
